### ISSUE TITLE
Delta - Read older versions using `versionAsOf`

### ISSUE THREAD

**Issue by JorisTruong** [SETL-Developers/setl#169]
## Describe the bug
I was looking to reproduce the piece of code from the Delta Quickstart [here](https://docs.delta.io/latest/quick-start.html#read-older-versions-of-data-using-time-travel):
```
df = spark.read.format("delta").option("versionAsOf", 0).load("/tmp/delta-table")
df.show()
```
in SETL by using a `Connector` and a configuration object like this:
```
deltaDataVersionZero {
  storage = "DELTA"
  path = <path>
  versionAsOf = "0"
  mode = "Overwrite"
}
```

However, the version 0 did not show up when I tried to read the `DataFrame`.

I think this is due to the `reader` in `DeltaConnector`. There are no `options` set and this is why the `versionAsOf` key is not taken into account.

## To Reproduce
We can reproduce this bug using `DeltaConnectorSuite` in the test named `"test Delta connector update"` line 82.

Adding this piece of code at the end, before `deltaConnector.drop()`:
```
val deltaConnectorOld = new DeltaConnector(DeltaConnectorConf.fromMap(
  Map[String, String](
    "path" -> path,
    "saveMode" -> saveMode.toString,
    "versionAsOf" -> "0"
  )
))

deltaConnectorOld.read().show(false)
```

We can see that the printed output is the updated data, while it should have been the data from `testTable`.

## Expected behavior
The reader in `DeltaConnector` should set the options.

**Comment by qxzzxq** [comment]
@maroil do you want to take a look at this issue?

**Comment by qxzzxq** [comment]
thanks for the pr :D

**Comment by maroil** [comment]
👍
