### ISSUE TITLE
How to enable Hive Support?

### ISSUE THREAD

**Issue by LiuxyEric** [SETL-Developers/setl#174]
I am trying to use spark.sql to read table from hive. However Setl cannot find my table. I read the source code and noticed that when initializing the SparkSession, it didn't enable hive support. So how am I able to read my table from hive? 
![image](https://user-images.githubusercontent.com/28945845/103595347-2a36e100-4f36-11eb-8769-2efc39367053.png)
usually I just called the code below to enable hive support.
``` scala
SparkSession.builder
      .enableHiveSupport
      .getOrCreate
```

**Comment by qxzzxq** [comment]
You can either add ` spark.sql.catalogImplementation = "hive"` into your `application.conf` (or other configuration files)

```
# src/main/resources/application.conf
setl.environment = ${app.environment}

setl.config {
  spark.app.name = "test_app"
  spark.sql.catalogImplementation = "hive"
}
```

or, you can use `Setl.builder().setSparkSession()` to provide your own spark session:

```scala
val sparkSession = SparkSession.builder().enableHiveSupport().getOrCreate()
val setl: Setl = Setl.builder()
  .setSparkSession(sparkSession)
  .withDefaultConfigLoader()
  .getOrCreate()
```

**Comment by LiuxyEric** [comment]
Thanks for the response !
